version: 0.2
phases:
  install:
    commands:
      - echo 'Nothing To Install'
      - ls -lrt      
  pre_build:
    commands:
      - echo 'In Pre Build'
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - docker version
      - docker pull 138871512076.dkr.ecr.us-west-2.amazonaws.com/pge-ecm-java:latest
      - docker tag 138871512076.dkr.ecr.us-west-2.amazonaws.com/pge-ecm-java:latest pge-ecm-java:latest
      - echo 'Pre Build Completed'
  build:
    commands:
      - echo '-----------------------------------------------------------------------------------------'
      - echo 'Creating CRMIS Search Microservice Image'
      - echo '-----------------------------------------------------------------------------------------'
      - docker build --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -t pge-ecm-crmis-search:latest .
      - docker tag pge-ecm-crmis-search:latest 138871512076.dkr.ecr.us-west-2.amazonaws.com/pge-ecm-crmis-search:latest
      - echo '-----------------------------------------------------------------------------------------'
      - echo 'Creating Docker Image And Tagging Completed Sucessfully'
      - echo '-----------------------------------------------------------------------------------------'
  post_build:
    commands:
      - echo '----------------------------------------------------------------------------------------'
      - echo 'Pushing CRMIS Search Image To Repository pge-ecm-crmis-search'
      - echo '-----------------------------------------------------------------------------------------'
      - docker push 138871512076.dkr.ecr.us-west-2.amazonaws.com/pge-ecm-crmis-search:latest
